### ISSUE TITLE
"dodgy, but trying to unregister anyway" on start

### ISSUE THREAD

**Issue by getochkn** [crowdrender/cr-docker#10] opened 2021-07-30 17:55 UTC
Here is a complete log from trying to run from the command line.  I used the correct token but hide it from here obviously.

root@Server:~# docker run -t  --name "Crowdrender-Server2"  -e "token=<HIDDEN>/"  --net=host zocker160/blender-crowdrender:beta
Unable to find image 'zocker160/blender-crowdrender:beta' locally
beta: Pulling from zocker160/blender-crowdrender
69692152171a: Pull complete 
0796c8418f29: Pull complete 
3d83dd03cdcb: Pull complete 
4436b827bd44: Pull complete 
c4c6e6367b7a: Pull complete 
e1441d19916c: Pull complete 
47dc695821fa: Pull complete 
728e9758f25e: Pull complete 
9c4a8d943a5d: Pull complete 
36db375ec3dd: Pull complete 
536e45ffc87c: Pull complete 
966bbade7a51: Pull complete 
Digest: sha256:a01d93db1f7f9c0e5b6543af6575a6a47bad66f804c9a86f80670e3e2d192dc1
Status: Downloaded newer image for zocker160/blender-crowdrender:beta
machine_uuid is not set...generating new unique UUID.....
downloading version latest of crowdrender......
using token for login....
your download token is: <HIDDEN>/
downloading latest CR version!
############################################################################################################################# 100.0%
installing crowdrender addon.......
Blender 2.93.0 (hash 84da05a8b806 built 2021-06-02 11:29:24)
Modules Installed () from '/CR/latest.zip' into '/root/.config/blender/2.93/scripts/addons'
Info: Modules Installed () from '/CR/latest.zip' into '/root/.config/blender/2.93/scripts/addons'
Info: Modules Installed () from '/CR/latest.zip' into '/root/.config/blender/2.93/scripts/addons'
Traceback (most recent call last):
  File "/usr/local/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'crowdrender'

Error: Traceback (most recent call last):
  File "/usr/local/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'crowdrender'

Error: Traceback (most recent call last):
  File "/usr/local/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'crowdrender'

Traceback (most recent call last):
  File "/CR/./install_addon.py", line 7, in <module>
    bpy.ops.preferences.addon_enable(module='crowdrender')
  File "/usr/local/blender/2.93/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/usr/local/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'crowdrender'

Blender quit
blender launch test:
Blender 2.93.0 (hash 84da05a8b806 built 2021-06-02 11:29:24)
Blender 2.93.0
        build date: 2021-06-02
        build time: 11:29:24
        build commit date: 2021-06-02
        build commit time: 11:21
        build hash: 84da05a8b806
        build platform: Linux
        build type: release
        build c flags:  -Wall -Wcast-align -Werror=implicit-function-declaration -Werror=return-type -Werror=vla -Wstrict-prototypes -Wmissing-prototypes -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wlogical-op -Wundef -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Wformat-signedness -Wrestrict -Wnonnull -Wabsolute-value -Wuninitialized -Wredundant-decls -Wshadow -Wno-error=unused-but-set-variable -Wimplicit-fallthrough=5  -fuse-ld=gold -std=gnu11 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -D_GLIBCXX_USE_CXX11_ABI=0  
        build c++ flags:  -Wuninitialized -Wredundant-decls -Wall -Wno-invalid-offsetof -Wno-sign-compare -Wlogical-op -Winit-self -Wmissing-include-dirs -Wno-div-by-zero -Wtype-limits -Werror=return-type -Wno-char-subscripts -Wno-unknown-pragmas -Wpointer-arith -Wunused-parameter -Wwrite-strings -Wundef -Wformat-signedness -Wrestrict -Wno-suggest-override -Wuninitialized -Wundef -Wmissing-declarations -Wimplicit-fallthrough=5  -fuse-ld=gold -std=c++17 -msse -pipe -fPIC -funsigned-char -fno-strict-aliasing -ffp-contract=off -msse2 -D_GLIBCXX_USE_CXX11_ABI=0  
        build link flags:  -Wl,--version-script='/home/blender/git/blender-v293/blender.git/source/creator/blender.map'
        build system: CMake
INFO: running in CPU only mode!
starting crowdrender server in CLOUD MODE.....................
Blender 2.93.0 (hash 84da05a8b806 built 2021-06-02 11:29:24)
OSError: Python file "/root/.config/blender/2.93/scripts/addons/crowdrender/src/py_3_9/serv_int_start.py" could not be opened: No such file or directory

**Comment by getochkn** [comment] 2021-07-30 23:06
Ok, my token was wrong for some reason.  I was able to get it installed, but now still get the 0.3.2 bug "dodgy, but trying to unregister anyway"  error.

How can install 0.3.1 for now from docker via command line?

**Comment by zocker-160** [comment] 2021-07-30 23:18
@getochkn thank you for reporting, we currently are experiencing some issue with 0.3.2 and we are working on it to fix it asap.

> How can install 0.3.1 for now from docker via command line?

Yes as stated in the readme, you can specify a specific version of the addon, by changing the `CR_VERSION` ENV variable
So in your case for 0.3.1, you need to set `CR_VERSION` to `cr_031_bl280` (`-e CR_VERSION cr_031_bl280`)

> dodgy, but trying to unregister anyway

this message can be ignored for now as long as you see the message, that the CR server has started successfully (we are working on improving this one as well)

EDIT: you need to make sure to change `CR_VERSION` back to `latest` if you want to have the latest version of CR again

**Comment by zocker-160** [comment] 2021-07-30 23:33
yes I can confirm that there is an issue currently, sadly it seems that the 0.3.1 image is also broken, I am really sorry about that.

**Comment by zocker-160** [comment] 2021-07-31 00:18
@getochkn would you please mind testing it again, I just pushed an update, which should fix this issue.

**Comment by tedztar** [comment] 2021-08-04 03:19
Hi,

I have just install the docker and I am also getting the same errors.
Any help would be apreciated.

**Comment by zocker-160** [comment] 2021-08-04 10:31
@tedztar do you mean the `dodgy, but trying to unregister anyway` message?

While we are working on fixing the warning message, it should still work.

**Comment by tedztar** [comment] 2021-08-04 21:30
@zocker-160 
after `Python file "/root/.config/blender/2.93/scripts/addons/crowdrender/src/py_3_9/serv_int_start.py" could not be opened: No such file or directory dodgy, but trying to unregister anyway`
I get a message saying `Crowed render addon disabled
Blender quit`

**Comment by zocker-160** [comment] 2021-08-04 21:57
@tedztar oh ok that is not good, what is your start command (without the token), which docker tag and are you sure you pulled the latest version?

Those information would be very useful for me to reproduce the error.

**Comment by tedztar** [comment] 2021-08-04 22:43
> @tedztar oh ok that is not good, what is your start command (without the token), which docker tag and are you sure you pulled the latest version?
> 
> Those information would be very useful for me to reproduce the error

And I am running the latest Docker

All I have done is use this to setup the docker
`docker run -t \
 --name "Crowdrender-Server" \
 -e token=<login_token> \
 --net=host \
zocker160/blender-crowdrender:latest`

EDIT:
Going to retry but specify to run on a local network as I all computers are on the same network. Will make another edit when I try.

**Comment by zocker-160** [comment] 2021-08-04 22:54
Could you try force pulling the latest container version?
Docker tends to use the one in cache instead of downloading the latest one.

You can force pull with: `docker pull zocker160/blender-crowdrender:latest`
and then run the `docker run` command again

**Comment by tedztar** [comment] 2021-08-04 23:52
Hi, ran the docker pull command and it said it was up to date already
then ran docker run and got the same error

**Comment by zocker-160** [comment] 2021-08-04 23:54
Could you please give me the entire log (make sure you erase your token from the log at the start) if possible?

**Comment by tedztar** [comment] 2021-08-05 00:23
[output.log](https://github.com/crowdrender/cr-docker/files/6935095/output.log)

**Comment by zocker-160** [comment] 2021-08-05 00:46
thank you for the log, looking at it it seems like the first time the download just failed (could be that server is having some issues)

`curl: (28) Operation timed out after 300264 milliseconds with 0 out of 0 bytes received`

And that is why the install fails.

On the second attempt the download seems to be starting, but sadly that is also where the log stops.

**Comment by tedztar** [comment] 2021-08-05 01:41
[crowdrender.log](https://github.com/crowdrender/cr-docker/files/6935329/crowdrender.log)
sorry about that this should be everything

**Comment by zocker-160** [comment] 2021-08-05 10:56
@tedztar ok so in this log you also have a download error, this time it is an SSL one

`curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 110`

so for some reason your download fails each time and then the install and start fails.

**Comment by Smilebags** [comment] 2021-08-06 09:09
Hi @tedztar, can you please try logging into https://discovery.crowd-render.com and then seeing whether this download succeeds?
https://discovery.crowd-render.com/api/v0/download-addon/latest

**Comment by arik123** [comment] 2021-08-07 12:20
I would like to report the same issue, here are the logs
[log.txt](https://github.com/crowdrender/cr-docker/files/6949052/log.txt)
and here is the command I used to start
```bash
sudo docker run -t \
 --name "Crowdrender-Server" \
 -e token=<token> \
 -e local=true \
 --net=host \
zocker160/blender-crowdrender:latest
```

**Comment by tedztar** [comment] 2021-08-08 05:24
> Hi @tedztar, can you please try logging into https://discovery.crowd-render.com and then seeing whether this download succeeds?
> https://discovery.crowd-render.com/api/v0/download-addon/latest

Yep I can download and it succeeded



> I would like to report the same issue, here are the logs
> [log.txt](https://github.com/crowdrender/cr-docker/files/6949052/log.txt)
> and here is the command I used to start
> 
> ```shell
> sudo docker run -t \
>  --name "Crowdrender-Server" \
>  -e token=<token> \
>  -e local=true \
>  --net=host \
> zocker160/blender-crowdrender:latest
> ```

Might want to regen your token now as you did not remove it from your log

**Comment by Smilebags** [comment] 2021-08-08 05:41
One other thing to ensure is that your email is verified. We have a check in place to ensure everyone downloading CrowdRender has verified  their email address, though since you were able to download from the website I don't expect that to be a problem.

**Comment by tedztar** [comment] 2021-08-08 05:48
Im pretty sure I did, Plus I am not getting any notificaions to verify anymore.
Question, do I need a ballence to use the docker on a LAN?

**Comment by Smilebags** [comment] 2021-08-08 05:50
No, you only need credit if you want to start up cloud servers through the addon. You can run the docker image just as you would run Blender with the addon installed, though you will need to ensure the different machines you want to use can talk to each other.

**Comment by tedztar** [comment] 2021-08-08 22:29
Hi Again, I just tried to use Ubuntu on another computer (I have 20+ hosts I want to get setup using docker) and I am getting the same error (Log attached) Brand new install aswell.
Thanks.
[ubuntu_output.log](https://github.com/crowdrender/cr-docker/files/6951540/ubuntu_output.log)

Just a note, it says running in Cloud mode even though I added `-e local=true` to the run command

**Comment by arik123** [comment] 2021-08-10 14:15
I would suggest you try commenting out [line 34 in start_cr_server.sh](https://github.com/crowdrender/cr-docker/blob/master/start_cr_server.sh#L34) and  [line 38 in start_cr_server_gpu.sh](https://github.com/crowdrender/cr-docker/blob/master/start_cr_server_gpu.sh#L38)
That did it for me

**Comment by zocker-160** [comment] 2021-08-13 13:58
thanks for the reports guys, I was on vacation, so please excuse my delayed response, I will look into this today to fix this.

**Comment by zocker-160** [comment] 2021-08-13 22:00
ok so update from my side: I found the issue, the main problem is, that the "ugly workaround" with overwriting the `BLENDER_PYV` var is flawed and does not work for non supporters, that get v0.3.0

I am working on a fix and I will push an update asap.

**Comment by zocker-160** [comment] 2021-08-13 23:27
@tedztar 
I just pushed an update, which should fix most of the issues mentioned here, please report back.

I also removed the token from the log, so you can now securely share your log.

**Comment by zocker-160** [comment] 2021-08-20 19:13
I will be closing this issue, since so far I have not gotten any new reports. If anyone still has an issue, please open an new issue.

**Closed as completed by zocker-160** 2021-08-20 19:13 UTC
Labels: enhancement
