### ISSUE TITLE
The docker image doesnt work on CR 0.3.2

### ISSUE THREAD

**Issue by Meowcat285** [crowdrender/cr-docker#9] opened 2021-07-27 00:08 UTC
Trying to start the container with CR version 0.3.2 results in the following error
`Traceback (most recent call last):
  File "/root/.config/blender/2.93/scripts/addons/crowdrender/src/py_3_9/serv_int_start.py", line 78, in <module>
    server_interface = crowdrender.src.py_3_9.server_interface
AttributeError: module 'crowdrender.src' has no attribute 'py_3_9'
dodgy, but trying to unregister anyway
Crowd Render add-on Disabled
`

**Comment by zocker-160** [comment] 2021-07-27 12:16
thank you for reporting this, I am looking into it

**Comment by zocker-160** [comment] 2021-07-27 12:26
can you tell me which docker image and tag you are using?

**Comment by Meowcat285** [comment] 2021-07-27 19:20
The :beta tag, but it also happens on the latest tag, but with a slightly different error.

> 
> 
> can you tell me which docker image and tag you are using?

**Comment by zocker-160** [comment] 2021-07-29 11:41
I am able to reproduce this issue, we are looking into it.

0.3.1 works fine, so only the latest version is affected.

**Comment by zocker-160** [comment] 2021-07-31 00:19
@Meowcat285 would you please mind testing it again, I just pushed an update, which should fix this issue.

**Comment by getochkn** [comment] 2021-07-31 00:29
That seemed to fix it.  Thank you for the fast support.  Glad to support the project.

**Comment by zocker-160** [comment] 2021-08-02 12:07
closing since this issues seems to be fixed

please reopen if this is not the case

**Closed as completed by zocker-160** 2021-08-02 12:07 UTC
Labels: bug
